#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# CairnIQ — Production Launcher
# ═══════════════════════════════════════════════════════════════
# Double-click to launch your private portfolio intelligence console
# Connected to your real account (Questrade, live data)
# ═══════════════════════════════════════════════════════════════

# Project directory. Desktop launchers generated by install.sh set
# CAIRNIQ_PROJECT_DIR so the launcher can live outside the repo.
if [[ -n "${CAIRNIQ_PROJECT_DIR:-}" ]]; then
    PROJECT_DIR="$CAIRNIQ_PROJECT_DIR"
else
    PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

cd "$PROJECT_DIR" 2>/dev/null || {
    echo "❌ ERROR: Could not find project directory"
    echo "Expected location: $PROJECT_DIR"
    echo ""
    echo "Press any key to close..."
    read -n1 -s
    exit 1
}

# Terminal styling
BOLD='\033[1m'
DIM='\033[2m'
GREEN='\033[38;5;42m'
CYAN='\033[38;5;51m'
BLUE='\033[38;5;39m'
PURPLE='\033[38;5;141m'
YELLOW='\033[38;5;226m'
RED='\033[38;5;196m'
GRAY='\033[38;5;240m'
NC='\033[0m'

# Clear screen and show fancy header
clear
echo ""
echo -e "${CYAN}${BOLD}"
echo "      ██████╗  █████╗ ██╗██████╗ ███╗   ██╗██╗ ██████╗ "
echo "     ██╔════╝ ██╔══██╗██║██╔══██╗████╗  ██║██║██╔═══██╗"
echo "     ██║      ███████║██║██████╔╝██╔██╗ ██║██║██║   ██║"
echo "     ██║      ██╔══██║██║██╔══██╗██║╚██╗██║██║██║▄▄ ██║"
echo "     ╚██████╗ ██║  ██║██║██║  ██║██║ ╚████║██║╚██████╔╝"
echo "      ╚═════╝ ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝ ╚══▀▀═╝ "
echo -e "${NC}"
echo -e "${PURPLE}${BOLD}                    P R I V A T E   P O R T F O L I O   I Q${NC}"
echo -e "${GRAY}                    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# System checks
echo -e "${BLUE}${BOLD}[SYSTEM CHECK]${NC} Initializing..."
echo ""

# Check virtual environment
if [[ ! -d ".venv" ]]; then
    echo -e "${RED}✗${NC} Virtual environment not found"
    echo -e "${GRAY}  Run ./install.sh first${NC}"
    echo ""
    echo "Press any key to close..."
    read -n1 -s
    exit 1
fi

echo -e "${GREEN}✓${NC} Virtual environment: ${GREEN}Active${NC}"
source .venv/bin/activate

# Check Python
PYTHON_VERSION=$(.venv/bin/python3 --version 2>&1 | cut -d' ' -f2)
echo -e "${GREEN}✓${NC} Python: ${GREEN}v${PYTHON_VERSION}${NC}"

# Check FAISS
if .venv/bin/python3 -c "import faiss" 2>/dev/null; then
    echo -e "${GREEN}✓${NC} FAISS Vector Search: ${GREEN}Enabled${NC}"
else
    echo -e "${YELLOW}⚠${NC} FAISS Vector Search: ${YELLOW}Fallback Mode${NC}"
fi

PORT="${PORT:-8000}"
URL="http://localhost:${PORT}"

LABEL="com.cairniq.server"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
DOMAIN="gui/$(id -u)"
ALERT_FILE="$PROJECT_DIR/user_data/ALERT_runaway.txt"

open_browser() {
    if command -v open &>/dev/null; then
        open "$URL"
    elif command -v xdg-open &>/dev/null; then
        xdg-open "$URL" >/dev/null 2>&1 || true
    else
        .venv/bin/python3 -m webbrowser "$URL" >/dev/null 2>&1 || true
    fi
}

port_open() { lsof -nP -iTCP:"$PORT" -sTCP:LISTEN &>/dev/null; }

# Check if port is already in use
if port_open; then
    echo ""
    echo -e "${YELLOW}${BOLD}[NOTICE]${NC} Server already running on port ${PORT}"
    echo -e "${GRAY}  Opening browser to existing instance...${NC}"
    echo ""
    open_browser
    sleep 2
    echo "Press any key to close..."
    read -n1 -s
    exit 0
fi

echo ""
echo -e "${BLUE}${BOLD}[LAUNCH]${NC} Starting CairnIQ..."
echo -e "${GRAY}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${CYAN}  🌐 Server:${NC}      ${URL}"
echo -e "${CYAN}  📊 Dashboard:${NC}   ${URL}/dashboard"
echo -e "${CYAN}  💬 Chat:${NC}        ${URL}/"
echo ""

# Ensure we're running in PRODUCTION mode (not demo)
unset DEMO_MODE
unset CAIRNIQ_FORCE_DEMO
unset DEMO_PROFILE
unset DEMO_RESET

echo -e "${GREEN}✓${NC} Mode: ${GREEN}Production (Your Account)${NC}"
echo ""

# ═══════════════════════════════════════════════════════════════
# Supervised start
# ═══════════════════════════════════════════════════════════════
# This launcher must NOT run server.py itself. A directly-run server becomes an
# unsupervised child of this Terminal window and wins the port race; launchd's
# own start then hits the single-instance guard in server.py and exits 0, and
# because the plist uses KeepAlive={SuccessfulExit: false} the job goes dormant
# instead of respawning. The result is a live server with no supervision at all,
# which stays down for good once it dies.
#
# So on macOS there is exactly ONE code path into the server: ask launchd.

# Wait for the server to bind the port. Startup is heavy (ticker downloads,
# agent init), so give it a couple of minutes before declaring failure.
wait_for_server() {
    local waited=0 limit=120
    echo -ne "${PURPLE}"
    while (( waited < limit )); do
        if port_open; then
            echo -e "${NC}"
            return 0
        fi
        echo -n "  ▓"
        sleep 3
        (( waited += 3 ))
    done
    echo -e "${NC}"
    return 1
}

start_supervised() {
    if [[ ! -f "$PLIST" ]]; then
        echo -e "${YELLOW}⚠${NC} Background service not installed yet"
        echo -e "${GRAY}  Installing it so CairnIQ runs supervised (auto-restart on crash, starts at login)${NC}"
        echo ""
        if ! "$PROJECT_DIR/scripts/install/setup_service.sh"; then
            echo -e "${RED}✗${NC} Could not install the background service"
            return 1
        fi
        return 0  # setup_service.sh loads the job, and RunAtLoad starts it
    fi

    if ! launchctl print "$DOMAIN/$LABEL" &>/dev/null; then
        # Plist exists but the job is not loaded. Either it was never
        # bootstrapped, or the watchdog booted it out after a runaway — in which
        # case it is meant to STAY down until a human has looked at it.
        if [[ -f "$ALERT_FILE" ]]; then
            echo -e "${RED}${BOLD}[WATCHDOG]${NC} The service was disabled after a runaway was detected:"
            echo ""
            echo -e "${GRAY}$(tail -n 3 "$ALERT_FILE")${NC}"
            echo ""
            echo -e "${GRAY}  Full log: ${ALERT_FILE}${NC}"
            echo ""
            read -r -p "Re-enable and start it anyway? [y/N] " reply
            if [[ ! "$reply" =~ ^[Yy]$ ]]; then
                echo -e "${GRAY}  Left disabled. Investigate, then delete the alert file when resolved.${NC}"
                return 1
            fi
        fi
        echo -e "${GRAY}  Loading background service...${NC}"
        launchctl bootstrap "$DOMAIN" "$PLIST" || return 1
        return 0  # RunAtLoad starts it
    fi

    # Job is loaded but nothing is listening — dormant, or still booting.
    # No -k: never kill an instance that may just be mid-startup.
    echo -e "${GRAY}  Asking launchd to start the service...${NC}"
    launchctl kickstart "$DOMAIN/$LABEL" || return 1
}

if command -v launchctl &>/dev/null; then
    if ! start_supervised; then
        echo ""
        echo -e "${RED}${BOLD}[FAILED]${NC} Could not start the background service"
        echo ""
        echo "Press any key to close..."
        read -n1 -s
        exit 1
    fi

    if wait_for_server; then
        echo -e "${GREEN}✓${NC} Server: ${GREEN}Running under launchd${NC} ${GRAY}(auto-restarts on crash)${NC}"
        echo ""
        open_browser
        echo -e "${GRAY}  Closing this window will NOT stop the server.${NC}"
        echo -e "${GRAY}  To stop it:  launchctl bootout ${DOMAIN}/${LABEL}${NC}"
        echo -e "${GRAY}  Logs:        tail -f logs/cairniq.stderr.log${NC}"
    else
        echo -e "${RED}✗${NC} Server did not come up within 2 minutes"
        echo -e "${GRAY}  Check: tail -n 40 logs/cairniq.stderr.log${NC}"
        echo ""
        echo "Press any key to close..."
        read -n1 -s
        exit 1
    fi
else
    # No launchd (e.g. Linux): there is no supervision to forfeit, so run the
    # server directly in this window, as before.
    echo -e "${GRAY}  launchd not available — running in this window${NC}"
    echo -e "${GRAY}  Press ${BOLD}Ctrl+C${NC}${GRAY} to stop the server${NC}"
    echo ""
    (sleep 3 && open_browser) &
    .venv/bin/python3 server.py
    echo ""
    echo -e "${RED}${BOLD}[SHUTDOWN]${NC} Server stopped"
fi

echo ""
echo "Press any key to close..."
read -n1 -s
